version: '2'
services:
    mongo:
        container_name: devdir_mongodb
        image: mongo
        ports:
            - "27018:27017"
    app:
        container_name: devdir_web_app
        build: .
        env_file: .env
        ports:
            - "7000:5000"
        volumes: 
            - .:/src
        links:
            - mongo
        depends_on:
            - mongo